sudo: false
language: ruby
install:
  - bundle install
  - npm install
script:
  - npm run compile
  - bundle exec ruby test.rb
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
branches:
  only:
    - gh-pages
    - /^.*$/
