name: Test

on:
  push:
    branches:
    - gh-pages
  pull_request:
    branches:
    - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn
    - name: Build and run tests
      run: |
        yarn run compile
        bundle exec ruby test.rb
