name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Set up Crystal
      run:
        curl -fsSL https://crystal-lang.org/install.sh | sudo bash
    - name: Install dependencies
      run: |
        shards install
        yarn
    - name: Build and run tests
      run: |
        yarn run compile
        crystal test.cr

